/**
 * Where a hermes:// deep link is handled. Pure — main.ts routes on the
 * result, tests assert the contract.
 *
 * 'quick-entry' — summon the ephemeral quick-entry popup in the main
 *   process. Used by the Windows Copilot hardware key: the MSIX manifest
 *   fragment (generated by electron-builder.config.cjs) registers the app
 *   as a copilotkeyprovider whose press activates
 *   <scheme>://copilot-key/start.
 *   A hardware key wants the lightweight composer, not the full window.
 * 'ignore' — activation noise that must not reach the renderer. The
 *   Copilot key's press-and-hold RELEASE fires copilot-key/stop; a tap
 *   fires start+stop nearly together, so acting on stop would undo the
 *   summon. Unknown copilot-key paths land here too.
 * 'renderer' — everything else: focus the main window and deliver the
 *   payload to the renderer's deep-link listener (blueprint links etc.).
 */
export type DeepLinkRoute = 'ignore' | 'quick-entry' | 'renderer'

export function routeDeepLink(kind: string, name: string): DeepLinkRoute {
  if (kind === 'copilot-key') {
    return name === 'start' ? 'quick-entry' : 'ignore'
  }

  return 'renderer'
}

/**
 * The deep-link protocol scheme this artifact owns. Each variant gets its
 * own: with a shared scheme the two side-by-side apps fight over the OS
 * handler registration and the Copilot key's activation URI can launch
 * the wrong app. Derived from the baked install stamp's payload — the
 * builder config derives the same value from its `light` flag
 * (electron-builder.config.cjs protocolScheme), so keep the two
 * derivations in agreement.
 */
export function deepLinkScheme(stampPayload: string | null | undefined): string {
  return stampPayload === 'light' ? 'hermes-light' : 'hermes'
}
